name: Sync to Koyeb

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync and Redeploy to Koyeb
        uses: koyeb/action-koyeb@v1
        with:
          api_token: ${{ secrets.KOYEB_TOKEN }}
          service_id: 905acb8a-258c-4f6b-a85f-406344473ad9?deploymentId=29f79dfe-00c2-4585-9200-c1dc59d191e8
